# Generated by Django 4.1 on 2022-08-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkInfor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WorkName_text', models.CharField(max_length=200)),
                ('Company_text', models.CharField(max_length=200)),
            ],
        ),
    ]
