# Generated by Django 4.1 on 2022-08-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostWorking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinfor',
            name='Description_text',
            field=models.CharField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='workinfor',
            name='Level',
            field=models.CharField(choices=[('inter', 'intership'), ('fresh', 'fresher'), ('sen', 'senior'), ('jun', 'junior')], default='intership', max_length=200),
        ),
        migrations.AlterField(
            model_name='workinfor',
            name='Company_text',
            field=models.CharField(default="'Company's name", max_length=200),
        ),
        migrations.AlterField(
            model_name='workinfor',
            name='WorkName_text',
            field=models.CharField(default="'work's name", max_length=200),
        ),
    ]
