# Generated by Django 4.1 on 2022-08-08 09:14

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('PostWorking', '0004_remove_workinfor_phonenumber_workinfor_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinfor',
            name='PhoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
