# Generated by Django 4.1 on 2022-08-08 09:15

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('PostWorking', '0005_alter_workinfor_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinfor',
            name='PhoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(default=0, max_length=128, null=True, region=None),
        ),
    ]
