# Generated by Django 4.1 on 2022-08-08 09:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostWorking', '0007_alter_workinfor_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workinfor',
            name='PhoneNumber',
        ),
        migrations.AddField(
            model_name='workinfor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
