# Generated by Django 4.1 on 2022-09-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostWorking', '0011_alter_workinfor_money_alter_workinfor_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinfor',
            name='photo',
            field=models.ImageField(blank=True, default=None, upload_to='WorkImages'),
        ),
    ]
