# Generated by Django 4.1 on 2022-09-12 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostWorking', '0012_alter_workinfor_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workinfor',
            name='Level',
        ),
        migrations.AddField(
            model_name='workinfor',
            name='level',
            field=models.CharField(choices=[('intership', 'intership'), ('fresher', 'fresher'), ('senior', 'senior'), ('junior', 'junior')], default='intership', max_length=200),
        ),
    ]
